spring:
  application:
    name: kafkatutorial
  kafka:
    security:
      protocol: SSL
    bootstrap-servers: localhost:9093
    # ssl:
    #   bundle:
    #     jks:
    #       vics-keystore:
    #         key:
    #           alias: "vics-app"
    #         keystore:
    #           location: "classpath:app.keystore.jks"
    #           password: "viciscool"
    #           type: "JKS"
    #       vic-truststore:
    #         truststore:
    #           location: "classpath:app.truststore.jks"
    #           password: "viciscool"
    #           type: "JKS"
    producer:
      ssl:
        trust-store-location: "classpath:ssl/app.truststore.jks"
        trust-store-password: "viciscool"
        key-store-location: "classpath:ssl/app.keystore.jks"
        key-store-password: "viciscool"
        key-password: "viciscool"
    consumer:
      group-id: customer-visit-group
      ssl:
        trust-store-location: "classpath:ssl/app.truststore.jks"
        trust-store-password: "viciscool"
        key-store-location: "classpath:ssl/app.keystore.jks"
        key-store-password: "viciscool"
        key-password: "viciscool"

vic:
  kafka:
    topic: customer.visit

